### ISSUE TITLE
Janus Client Example

### ISSUE THREAD

**Issue by kinsleykajiva** [Charles92011/webrtc-java-experimental-server#1]
hi, I have been looking around do you have a Janus java fx example of the implementation of of the java webrtc example, I really need help please?

I have tried to run the wiki examples I cant get ice candidates for me to send to the Janus to sever also the SDP has missing media info as well .

**Comment by Charles92011** [comment]
@kinsleykajiva I don't have an example of connecting this project to Janus. It's outside of my needs, so I haven't tried it.
It could be done by connecting to Janus using the Janus websocket API.

**Comment by kinsleykajiva** [comment]
ok thanks

**Comment by Charles92011** [comment]
I am interested in pursuing this, it's an interesting pursuit.
Let's move the talk to discussions
